#!/usr/bin/env bash

DEBUG_STR="Debug: "

function do_update()
{
    source_file=$1
    link_file=$2

    if [ -e $link_file ]; then
        echo $DEBUG_STR" Delete old file(s): \"$link_file\""
        rm $link_file
    fi

    ln -s $source_file $link_file
}

source_file="$PWD/bash_aliases"
target_file="$HOME/.bash_aliases"
do_update $source_file $target_file

source_file="$PWD/bashrc"
target_file="$HOME/.bashrc"
do_update $source_file $target_file

source_file="$PWD/vimrc"
target_file="$HOME/.vimrc"
do_update $source_file $target_file

source_file="$PWD/vim"
target_file="$HOME/.vim"
do_update $source_file $target_file

source_file="$PWD/gitconfig"
target_file="$HOME/.gitconfig"
do_update $source_file $target_file

source_file="$PWD/dput.cf"
target_file="$HOME/.dput.cf"
do_update $source_file $target_file

source_file="$PWD/bin"
target_file="$HOME/bin"
do_update $source_file $target_file

source_file="$PWD/defaults.list"
target_file="$HOME/.local/share/applications/defaults.list"
do_update $source_file $target_file

echo 'You must exit this shell and login again to enable new configuration(s).'
