#!/usr/bin/env bash

DEBUG_STR="Debug: "

function do_update()
{
    source_file=$1
    link_file=$2

    if [ -e $link_file ]; then
        echo $DEBUG_STR" Delete old file(s): \"$link_file\""
        rm $link_file
    fi

    ln -s $source_file $link_file
}

# bashrc and bash_aliases
source_file="$PWD/aliases"
target_file="$HOME/.aliases"
do_update $source_file $target_file

source_file="$PWD/inputrc"
target_file="$HOME/.inputrc"
do_update $source_file $target_file

source_file="$PWD/bashrc"
target_file="$HOME/.bashrc"
do_update $source_file $target_file
echo 'You must exit this shell and login again to enable new configuration(s).'

source_file="$PWD/zshrc"
target_file="$HOME/.zshrc"
do_update $source_file $target_file

# vim settings
source_file="$PWD/vimrc"
target_file="$HOME/.vimrc"
do_update $source_file $target_file

source_file="$PWD/vim"
target_file="$HOME/.vim"
do_update $source_file $target_file

# emacs settings
source_file="$PWD/emacsrc"
target_file="$HOME/.emacs"
do_update $source_file $target_file

source_file="$PWD/emacs"
target_file="$HOME/.emacs.d"
do_update $source_file $target_file

# git settings
source_file="$PWD/gitconfig"
target_file="$HOME/.gitconfig"
do_update $source_file $target_file

# launchpad settings
source_file="$PWD/dput.cf"
target_file="$HOME/.dput.cf"
do_update $source_file $target_file

# custom commands
source_file="$PWD/bin"
target_file="$HOME/bin"
do_update $source_file $target_file

# irssi settings
source_file="$PWD/irssi"
target_file="$HOME/.irssi"
do_update $source_file $target_file

# tmux settings
source_file="$PWD/tmux.conf"
target_file="$HOME/.tmux.conf"
do_update $source_file $target_file

# tmuxifier settings
source_file="$PWD/tmuxifier"
target_file="$HOME/.tmuxifier"
do_update $source_file $target_file
source_file="$PWD/tmuxifier-layouts"
target_file="$HOME/.tmuxifier-layouts"
do_update $source_file $target_file

#file="$HOME/.local/share/applications/mimeapps.list"
#if [ -e $file ]; then
#    echo $DEBUG_STR" Delete old file(s): \"$file\""
#    rm $file
#fi
#source_file="$PWD/defaults.list"
#target_file="$HOME/.local/share/applications/defaults.list"
#do_update $source_file $target_file

